### ISSUE TITLE
Release on PyPI for pip install

### ISSUE THREAD

**Issue by techtonik** [mozilla/pymake#23]
This worked for me on Windows without having to install bash and friends. Sphinx and other cross-platform tools that historically use Makefiles for automation can surely benefit from this package if it could be made available through PyPI

**Comment by techtonik** [comment]
@bsmedberg will this project be maintained further by Mozilla? I find it pretty exciting to have a Makefile parser available in Python. I can see that it could be used in projects like `scons`.

**Comment by bsmedberg** [comment]
I am no longer maintaining this, and Mozilla doesn't use it. So you should feel free to fork it and become the "true head" if you want to maintain it.

**Comment by techtonik** [comment]
I am not sure I have the capacity. Maybe a few fixes here and there, but maintaining would be hard.

**Comment by indygreg** [comment]
I would upload a package to PyPI. However, somebody has already reserved the "pymake" name on PyPI. There aren't any releases and I'm unable to see who has registered it. (You can find the package name in the list at https://pypi.python.org/simple/).

**Comment by techtonik** [comment]
@indygreg if you open PyPI support tracker http://sourceforge.net/tracker/?group_id=66150&atid=513504 there is a chance that somebody from PyPI could help with that.

**Comment by techtonik** [comment]
@indygreg created https://sourceforge.net/p/pypi/support-requests/670/
